# Use this in your UnturnedImages/config.yaml file
- Id: "7458-7483;7490-7491" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/1731386750/items/{ItemId}.png" # The repository of the override.