# Use this in your UnturnedImages/config.yaml file
- Id: "1538-1542;1548-1551;9000-9006;9009-9022;9024-9034;9037-9055;9108" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/1767554683/items/{ItemId}.png" # The repository of the override.