# Use this in your UnturnedImages/config.yaml file
- Id: "4734-4741;4743-4749;4755-4759" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/1731384487/items/{ItemId}.png" # The repository of the override.