# Use this in your UnturnedImages/config.yaml file
- Id: "7513-7521;79607960;7964-7986;7990-8003" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/1815076333/items/{ItemId}.png" # The repository of the override.