# Use this in your UnturnedImages/config.yaml file
- Id: "56001-56027;56180" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/2014624499/items/{ItemId}.png" # The repository of the override.