# Use this in your UnturnedImages/config.yaml file
- WorkshopId: "2069342497" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/2069342497/items/{ItemId}.png" # The repository of the override.