# Use this in your UnturnedImages/config.yaml file
- WorkshopId: "1979157694" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/1979157694/items/{ItemId}.png" # The repository of the override.