# Use this in your UnturnedImages/config.yaml file
- Id: "17201-17205;17207-17210;1721317213;17215-17216;17218-17245;17248-17249" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/2117291360/items/{ItemId}.png" # The repository of the override.