# Use this in your UnturnedImages/config.yaml file
- WorkshopId: "2528363491" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/2528363491/vehicles/{VehicleId}.png" # The repository of the override.