# Use this in your UnturnedImages/config.yaml file
- WorkshopId: "2454681372" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/2454681372/items/{ItemId}.png" # The repository of the override.