# Use this in your UnturnedImages/config.yaml file
- Id: "23500-23553" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/2886891791/items/{ItemId}.png" # The repository of the override.