# Use this in your UnturnedImages/config.yaml file
- Id: "53001" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/1992424576/items/{ItemId}.png" # The repository of the override.